/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 FlowerBed.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/FlowerBed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FlowerBed2_1.geometry} material={materials.ConcreteFlowerBed2} />
      <mesh geometry={nodes.FlowerBed2_2.geometry} material={materials.GroundFlowerBed5} />
    </group>
  )
}

useGLTF.preload('/FlowerBed.glb')
