/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Grass2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Grass2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh1_ElwFor_Grass01_C01_1_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh2_ElwFor_Grass01_C01_2_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh3_ElwFor_Grass01_C02_1_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh4_ElwFor_Grass01_C01_3_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh5_ElwFor_Grass01_C02_2_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh6_ElwFor_Grass01_C02_3_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh7_ElwFor_Grass01_C02_4_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh8_ElwFor_Grass01_C02_5_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh9_ElwFor_Grass01_C02_6_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh10_ElwFor_Grass01_C02_7_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh11_ElwFor_Grass01_C02_8_Model.geometry} material={materials._4} />
      <mesh geometry={nodes.Mesh12_ElwFor_Grass01_C01_4_Model.geometry} material={materials._4} />
    </group>
  )
}

useGLTF.preload('/Grass2.glb')
