/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Marigold.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Marigold.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DesertMarigold_mesh.geometry} material={materials.DesertMarigold_mat} />
    </group>
  )
}

useGLTF.preload('/Marigold.glb')
