/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ShojiWall.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ShojiWall.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh geometry={nodes.Wall_Shoji_1.geometry} material={materials.Atlas} />
        <mesh geometry={nodes.Wall_Shoji_2.geometry} material={materials.Light} />
      </group>
    </group>
  )
}

useGLTF.preload('/ShojiWall.glb')
