/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 StoneWalkway.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/StoneWalkway.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['walkway-stone'].geometry} material={materials['Texture-base.014']} scale={100} />
    </group>
  )
}

useGLTF.preload('/StoneWalkway.glb')
